name: CI Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run coverage
      uses: matheusvanzan/django-coverage-action@master
      with:
      - django-app: 'main'
      - minimum-coverage: '50'