# This is a basic workflow to help you get started with Actions

name: CI Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types: # This configuration does not affect the page_build event above
      - created

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      env:
        SSHPASS: ${{ secrets.SERVER_PASS }}
      run: >-
        sshpass 
        -e ssh 
        -o StrictHostKeyChecking=no
        ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:
        "ls"
