name: CI Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Pre processing
      run: |
        sudo apt-get update
        sudo apt-get install nmap
        nmap -Pn ${{ secrets.SERVER_HOST }}

    - name: SSH Access
      env:
        SSHPASS: ${{ secrets.SERVER_PASS }}
      run: >-
        sshpass 
        -e ssh 
        -o StrictHostKeyChecking=no
        ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:
        "ls"
