name: CI Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: SSH Access
      env:
        SSHPASS: ${{ secrets.SERVER_PASS }}
      run: >-
        sshpass -e ssh -o StrictHostKeyChecking=no
        ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
        cd /home/vanzan/production/django-umcodigo 
        && git pull https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git
        && echo ${{ secrets.SERVER_PASS }} | sudo systemctl restart django-umcodigo
        && echo ${{ secrets.SERVER_PASS }} | sudo systemctl restart nginx
        && exit"
        
