name: Deploy

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: SSH Access
      env:
        SSHPASS: ${{ secrets.SERVER_PASS }}
      run: >-
        sshpass -e ssh -o StrictHostKeyChecking=no
        ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
        cd /home/vanzan/production/django-umcodigo 
        && git pull https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git
        && source ../env/django-umcodigo/bin/activate
        && pip install -r requirements.txt
        && python manage.py migrate
        && echo ${{ secrets.SERVER_PASS }} | sudo -S systemctl restart django-umcodigo
        && echo ${{ secrets.SERVER_PASS }} | sudo -S systemctl restart nginx
        && exit"
        
