# This is a basic workflow to help you get started with Actions

name: CI Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Runs a set of commands using the runners shell
    - name: Install dependencies
      run: sudo apt-get install python3 python3-dev virtualenv
        

    # Runs a set of commands using the runners shell
    - name: Install virtualenv
      env:
        SOCIAL_AUTH_FACEBOOK_KEY: ${{ secrets.SOCIAL_AUTH_FACEBOOK_KEY }}
        SOCIAL_AUTH_FACEBOOK_SECRET: ${{ secrets.SOCIAL_AUTH_FACEBOOK_SECRET }}
        SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: ${{ secrets.SOCIAL_AUTH_GOOGLE_OAUTH2_KEY }}
        SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: ${{ secrets.SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET }}
      run: |
        cd $GITHUB_WORKSPACE
        virtualenv --python=$(which python3) env
        source env/bin/activate
        pip install -r requirements.txt
        python manage.py test
        ls
        
    # Runs a set of commands using the runners shell
    - name: Step that should not run
      run: |
        cd ..
        ls
